import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { IntakeFormData } from '@/features/intake/types/intake';

// Extend jsPDF with autotable types
interface jsPDFWithAutoTable extends jsPDF {
    autoTable: (options: any) => jsPDF;
}

export class ReportGenerator {
    static generateDORIntakeReport(formData: IntakeFormData) {
        const doc = new jsPDF() as jsPDFWithAutoTable;
        const margin = 20;
        let y = 20;

        // Header
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229); // Accent color
        doc.text('New Beginning Success Plan', margin, y);

        y += 10;
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text('Department of Rehabilitation - Individual Service Plan (ISP)', margin, y);

        y += 15;
        doc.setDrawColor(226, 232, 240);
        doc.line(margin, y, 190, y);

        // Client Info Table
        y += 10;
        doc.autoTable({
            startY: y,
            head: [['Field', 'Client Information']],
            body: [
                ['Client Name', formData.clientName],
                ['Email', formData.email || 'N/A'],
                ['Phone', formData.phone || 'N/A'],
                ['Intake Date', formData.reportDate],
                ['SSN Last 4', `***-**-${formData.ssnLastFour}`],
            ],
            theme: 'striped',
            headStyles: { fillStyle: [79, 70, 229] },
        });

        y = (doc as any).lastAutoTable.finalY + 15;

        // Goals Section
        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text('Individual Service Goals', margin, y);
        y += 10;

        doc.autoTable({
            startY: y,
            head: [['Path', 'Objectives & Stability Plan']],
            body: [
                ['Employment', formData.employmentGoals || 'No goals specified'],
                ['Education', formData.educationGoals || 'No education objectives'],
                ['Housing', formData.housingNeeds || 'Housing stable'],
            ],
            theme: 'grid',
            headStyles: { fillStyle: [30, 41, 59] },
        });

        y = (doc as any).lastAutoTable.finalY + 15;

        // Readiness & Prep
        doc.setFontSize(14);
        doc.text('Employment Preparation Curriculum', margin, y);
        y += 10;

        const prepItems = [
            ['Fair Chance Hiring', formData.class1Date || 'Pending'],
            ['Interview Techniques', formData.class2Date || 'Pending'],
            ['Work Behaviors', formData.class3Date || 'Pending'],
            ['Hygiene & Grooming', formData.class4Date || 'Pending'],
            ['Master App Complete', formData.masterAppComplete ? 'YES' : 'NO'],
            ['Resume Complete', formData.resumeComplete ? 'YES' : 'NO'],
        ];

        doc.autoTable({
            startY: y,
            head: [['Module', 'Status/Completion Date']],
            body: prepItems,
            theme: 'striped',
        });

        // Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(148, 163, 184);
            doc.text(
                `Generated by New Beginning Platform on ${new Date().toLocaleDateString()} - Confidential`,
                margin,
                285
            );
        }

        doc.save(`DOR_Report_${formData.clientName.replace(/\s+/g, '_')}.pdf`);
    }
}
